// Generated by CoffeeScript 1.10.0
(function() {
  var Draw, Init, Load, Update, zeldroid;

  Torch.StrictErrors();

  Torch.DisableConsoleWarnings();

  zeldroid = new Zeldroid("container", "fill", "fill", "TheGame", Torch.CANVAS);

  Load = function(game) {
    game.Bounds();
    Player.Load(game);
    HUD.Load(game);
    game.Load.Texture("Assets/Art/map/bush.png", "bush");
    game.Load.Texture("Assets/Art/map/water.png", "water");
    return game.Load.File("Maps/test-map-2.map", "map");
  };

  Init = function(game) {
    game.Clear("#fcd8a8");
    game.PixelScale();
    Torch.Scale = 4;
    game.player = new Player(game);
    game.mapManager = new MapManager(game);
    game.hud = new HUD(game);
    game.debugCondole = new Torch.DebugConsole(game);
    return game.debugCondole.AddCommand("SPAWN", function(tConsole, x, y) {});
  };

  Draw = function(game) {};

  Update = function(game) {
    if (game.deltaTime > 1000 / 50) {
      return alert("FPS Dipped! " + game.deltaTime);
    }
  };

  zeldroid.Start(Load, Update, Draw, Init);

  window.zeldroid = zeldroid;

}).call(this);
