// Generated by CoffeeScript 1.10.0
(function() {
  var Zeldroid,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Zeldroid = (function(superClass) {
    extend(Zeldroid, superClass);

    function Zeldroid() {
      return Zeldroid.__super__.constructor.apply(this, arguments);
    }

    return Zeldroid;

  })(Torch.Game);

  window.Zeldroid = Zeldroid;

}).call(this);
