// Generated by CoffeeScript 1.10.0
(function() {
  var EffectManager;

  EffectManager = (function() {
    EffectManager.prototype.tint = null;

    EffectManager.prototype.mask = null;

    function EffectManager(sprite) {
      this.sprite = sprite;
      this.tint = {
        color: null,
        opacity: 0.5
      };
      this.mask = {
        texture: null,
        "in": false,
        out: false
      };
    }

    return EffectManager;

  })();

  Torch.EffectManager = EffectManager;

}).call(this);
