// Generated by CoffeeScript 1.10.0
(function() {
  var Size;

  Size = (function() {
    Size.prototype.width = 0;

    Size.prototype.height = 0;

    Size.prototype.scale = null;

    function Size(sprite) {
      var rect;
      this.sprite = sprite;
      rect = this.sprite.rectangle;
    }

    return Size;

  })();

}).call(this);
