// Generated by CoffeeScript 1.10.0
(function() {
  var Size;

  Size = (function() {
    Size.prototype.width = 0;

    Size.prototype.height = 0;

    Size.prototype.scale = null;

    function Size(sprite) {
      var rect;
      this.sprite = sprite;
      rect = this.sprite.rectangle;
      this.width = rect.width;
      this.height = rect.height;
      this.scale = {
        width: 1,
        height: 1
      };
    }

    Size.prototype.Update = function() {
      var rect;
      rect = this.sprite.rectangle;
      rect.width = this.width * this.scale.width;
      return rect.height = this.height * this.scale.height;
    };

    Size.prototype.Set = function(width, height) {
      this.width = width;
      return this.height = height;
    };

    Size.prototype.Scale = function(widthScale, heightScale) {
      this.scale.width = widthScale;
      return this.scale.height = heightScale;
    };

    return Size;

  })();

  Torch.Size = Size;

}).call(this);
