// Generated by CoffeeScript 1.10.0
(function() {
  var CollisionDetector;

  CollisionDetector = (function() {
    function CollisionDetector(sprite, otherSprite) {
      this.sprite = sprite;
      this.otherSprite = otherSprite;
    }

    CollisionDetector.prototype.AABB = function() {
      return new AABB(this.sprite, this.otherSprite).Execute();
    };

    CollisionDetector.prototype.Circle = function() {
      return new Circle(this.sprite, this.otherSprite).Execute();
    };

    CollisionDetector.prototype.SAT = function() {
      return new SAT(this.sprite, this.otherSprite).Execute();
    };

    return CollisionDetector;

  })();

}).call(this);
