// Generated by CoffeeScript 1.12.1
(function() {
  var Blob, Enemy, exports,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  exports = this;

  Enemy = (function(superClass) {
    extend(Enemy, superClass);

    function Enemy() {
      return Enemy.__super__.constructor.apply(this, arguments);
    }

    Enemy.prototype.hardBlock = true;

    Enemy.prototype.hp = 3;

    Enemy.prototype.ENEMY = true;

    Enemy.prototype.identifier = 200;

    Enemy.Load = function(game) {
      return game.Load.Texture("Assets/Art/enemies/blob.png", "blob");
    };

    return Enemy;

  })(MapPieces.MapPiece);

  Blob = (function(superClass) {
    extend(Blob, superClass);

    function Blob() {
      return Blob.__super__.constructor.apply(this, arguments);
    }

    Blob.prototype.textureId = "blob";

    Blob.prototype.identifier = 201;

    return Blob;

  })(Enemy);

  Torch.ExtendObject(MapPieces, {
    Blob: Blob
  });

  exports.Enemy = Enemy;

}).call(this);
