// Generated by CoffeeScript 1.12.1
(function() {
  var Blob, Enemy, exports,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  exports = this;

  Enemy = (function(superClass) {
    extend(Enemy, superClass);

    function Enemy() {
      return Enemy.__super__.constructor.apply(this, arguments);
    }

    Enemy.prototype.hardBlock = true;

    Enemy.prototype.hp = 3;

    Enemy.prototype.ENEMY = true;

    Enemy.prototype.identifier = 200;

    Enemy.Load = function(game) {
      return game.Load.Texture("Assets/Art/enemies/blob.png", "blob");
    };

    return Enemy;

  })(MapPieces.MapPiece);

  Blob = (function(superClass) {
    extend(Blob, superClass);

    function Blob() {
      return Blob.__super__.constructor.apply(this, arguments);
    }

    Blob.prototype.textureId = "blob";

    Blob.prototype.identifier = 201;

    return Blob;

  })(Enemy);

  Torch.ExtendObject(MapPieces, {
    Blob: Blob
  });

  exports.Enemy = Enemy;

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiRW5lbXkuanMiLCJzb3VyY2VSb290IjoiLi5cXC4uXFwuLlxcLi5cXC4uIiwic291cmNlcyI6WyJHYW1lc1xcWmVsZHJvaWRcXFNyY1xcTWFwUGllY2VzXFxFbmVtaWVzXFxFbmVteS5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBO0FBQUEsTUFBQSxvQkFBQTtJQUFBOzs7RUFBQSxPQUFBLEdBQVU7O0VBRUo7Ozs7Ozs7b0JBQ0YsU0FBQSxHQUFXOztvQkFDWCxFQUFBLEdBQUk7O29CQUNKLEtBQUEsR0FBTzs7b0JBQ1AsVUFBQSxHQUFZOztJQUVaLEtBQUMsQ0FBQSxJQUFELEdBQU8sU0FBQyxJQUFEO2FBQ0gsSUFBSSxDQUFDLElBQUksQ0FBQyxPQUFWLENBQWtCLDZCQUFsQixFQUFpRCxNQUFqRDtJQURHOzs7O0tBTlMsU0FBUyxDQUFDOztFQVN4Qjs7Ozs7OzttQkFDRixTQUFBLEdBQVc7O21CQUNYLFVBQUEsR0FBWTs7OztLQUZHOztFQUtuQixLQUFLLENBQUMsWUFBTixDQUFtQixTQUFuQixFQUNJO0lBQUEsSUFBQSxFQUFNLElBQU47R0FESjs7RUFJQSxPQUFPLENBQUMsS0FBUixHQUFnQjtBQXBCaEIiLCJzb3VyY2VzQ29udGVudCI6WyJleHBvcnRzID0gdGhpc1xyXG5cclxuY2xhc3MgRW5lbXkgZXh0ZW5kcyBNYXBQaWVjZXMuTWFwUGllY2VcclxuICAgIGhhcmRCbG9jazogdHJ1ZVxyXG4gICAgaHA6IDNcclxuICAgIEVORU1ZOiB0cnVlXHJcbiAgICBpZGVudGlmaWVyOiAyMDBcclxuXHJcbiAgICBATG9hZDogKGdhbWUpIC0+XHJcbiAgICAgICAgZ2FtZS5Mb2FkLlRleHR1cmUoXCJBc3NldHMvQXJ0L2VuZW1pZXMvYmxvYi5wbmdcIiwgXCJibG9iXCIpXHJcblxyXG5jbGFzcyBCbG9iIGV4dGVuZHMgRW5lbXlcclxuICAgIHRleHR1cmVJZDogXCJibG9iXCJcclxuICAgIGlkZW50aWZpZXI6IDIwMVxyXG5cclxuXHJcblRvcmNoLkV4dGVuZE9iamVjdCBNYXBQaWVjZXMsXHJcbiAgICBCbG9iOiBCbG9iXHJcblxyXG5cclxuZXhwb3J0cy5FbmVteSA9IEVuZW15XHJcbiJdfQ==
//# sourceURL=C:\dev\js\Torch.js\Games\Zeldroid\Src\MapPieces\Enemies\Enemy.coffee