// Generated by CoffeeScript 1.11.1
(function() {
  var Draw, Game, Init, Load, Update;

  Torch.StrictErrors();

  Torch.DisableConsoleWarnings();

  Game = new Torch.Game("container", "fill", "fill", "TheGame", Torch.WEBGL);

  Load = function(game) {
    game.Bounds();
    return game.Load.Texture("Art/player.png", "player");
  };

  Init = function(game) {
    var player;
    Torch.Scale = 6;
    game.Add(new Torch.AmbientLight(0xffffff));
    return player = new Player(game);
  };

  Draw = function(game) {};

  Update = function(game) {};

  Game.Start(Load, Update, Draw, Init);

}).call(this);
