// Generated by CoffeeScript 1.10.0
(function() {
  var HUD, exports;

  exports = this;

  HUD = (function() {
    function HUD(game) {
      this.game = game;
    }

    return HUD;

  })();

  exports.HUD = HUD;

}).call(this);
