// Generated by CoffeeScript 1.10.0
(function() {
  var HUD, exports;

  exports = this;

  HUD = (function() {
    function HUD(game) {
      this.game = game;
      this.hud_background = new Torch.Sprite(this.game, 0, 0);
      this.hud_background.Scale(1);
      this.hud_background.Bind.Texture("hud_background");
      this.hud_background.DrawIndex(100);
    }

    return HUD;

  })();

  exports.HUD = HUD;

}).call(this);
