// Generated by CoffeeScript 1.10.0
(function() {
  var MapManager, exports;

  exports = this;

  MapManager = (function() {
    function MapManager(game) {
      var key, piece;
      this.game = game;
      this.Parts = [];
      this.pieces = [];
      for (key in MapPieces) {
        piece = MapPieces[key];
        this.Parts[piece.prototype.identifier] = piece;
      }
    }

    MapManager.prototype.LoadMap = function(fileId) {
      var i, identifier, index, j, len, len1, mapString, metaData, pieces, ref, results, seg, segment, segments, segs, sp;
      mapString = this.game.File(fileId);
      sp = mapString.split("\n");
      metaData = sp[0];
      mapString = sp[1];
      segments = mapString.split(";");
      pieces = [];
      results = [];
      for (i = 0, len = segments.length; i < len; i++) {
        segment = segments[i];
        if (segment === "") {
          break;
        }
        identifier = segment.split(",")[0];
        segs = [];
        ref = segment.split(",");
        for (index = j = 0, len1 = ref.length; j < len1; index = ++j) {
          seg = ref[index];
          if (index !== 0 && seg !== "") {
            segs.push(seg);
          }
        }
        results.push(pieces.push(new this.Parts[identifier](this.game, segs)));
      }
      return results;
    };

    return MapManager;

  })();

  exports.MapManager = MapManager;

}).call(this);
