// Generated by CoffeeScript 1.10.0
(function() {
  var MapManager;

  MapManager = (function() {
    function MapManager(game) {
      this.game = game;
      this.Parts = {};
    }

    MapManager.prototype.LoadMap = function(fileId) {
      var i, identifier, index, j, len, len1, mapString, pieces, ref, results, seg, segment, segments, segs;
      mapString = this.game.File(fileId);
      segments = mapString.split(";");
      pieces = [];
      results = [];
      for (i = 0, len = segments.length; i < len; i++) {
        segment = segments[i];
        identifier = segment.split(",")[0];
        segs = [];
        ref = segments.split(",");
        for (index = j = 0, len1 = ref.length; j < len1; index = ++j) {
          seg = ref[index];
          if (index !== 0) {
            segs.push(seg);
          }
        }
        results.push(pieces.push(new this.Parts[identifier](segs)));
      }
      return results;
    };

    return MapManager;

  })();

}).call(this);
