// Generated by CoffeeScript 1.10.0
(function() {
  var Player,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Player = (function(superClass) {
    extend(Player, superClass);

    function Player(game) {
      this.InitSprite(game, 0, 0);
      this.Bind.Texture("player");
      this.Center().CenterVertical();
      this.On("Collision", (function(_this) {
        return function(event) {
          var offset;
          offset = event.collisionData;
          if (offset.vx < offset.halfWidths && offset.vy < offset.halfHeights) {
            if (offset.x < offset.y) {
              if (offset.vx > 0) {
                return _this.Move("x", offset.x / 2);
              } else if (offset.vx < 0) {
                return _this.Move("x", -offset.x / 2);
              }
            } else if (offset.x > offset.y) {
              if (offset.vy > 0) {
                return _this.Move("y", offset.y / 2);
              } else if (offset.vy < 0) {
                return _this.Move("y", -offset.y / 2);
              }
            }
          }
        };
      })(this));
    }

    Player.prototype.Update = function() {
      var keys;
      Player.__super__.Update.call(this);
      keys = this.game.Keys;
      this.Velocity("x", 0).Velocity("y", 0);
      if (keys.D.down) {
        this.Velocity("x", 1);
      }
      if (keys.A.down) {
        this.Velocity("x", -1);
      }
      if (keys.S.down) {
        this.Velocity("y", 1);
      }
      if (keys.W.down) {
        return this.Velocity("y", -1);
      }
    };

    return Player;

  })(Torch.Sprite);

  window.Player = Player;

}).call(this);
