// Generated by CoffeeScript 1.10.0
(function() {
  var Player,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Player = (function(superClass) {
    extend(Player, superClass);

    Player.prototype.VELOCITY = 0.4;

    function Player(game) {
      this.InitSprite(game, 0, 0);
      this.Bind.Texture("player");
      this.Center().CenterVertical();
      this.On("Collision", (function(_this) {
        return function(event) {
          _this.Collisions.SimpleCollisionHandle(event);
          return _this.Velocity("x", 0).Velocity("y", 0);
        };
      })(this));
    }

    Player.prototype.Update = function() {
      var keys;
      Player.__super__.Update.call(this);
      keys = this.game.Keys;
      this.Velocity("x", 0).Velocity("y", 0);
      if (keys.D.down) {
        this.Velocity("x", this.VELOCITY);
      }
      if (keys.A.down) {
        this.Velocity("x", -this.VELOCITY);
      }
      if (keys.S.down) {
        this.Velocity("y", this.VELOCITY);
      }
      if (keys.W.down) {
        return this.Velocity("y", -this.VELOCITY);
      }
    };

    return Player;

  })(Torch.Sprite);

  window.Player = Player;

}).call(this);
