// Generated by CoffeeScript 1.10.0
(function() {
  var Draw, Game, Init, Load, Update, blueLightMover;

  Torch.StrictErrors();

  Game = new Torch.Game("container", "fill", "fill", "Void", Torch.WEBGL);

  blueLightMover = 0;

  Load = function(game) {
    game.Load.Texture("Art/ship.png", "player");
    game.Load.Texture("Art/player.png", "black");
    game.Load.Texture("Art/enemy.png", "enemy");
    return game.Load.Texture("Art/bullet.png", "bullet");
  };

  Init = function(game) {
    Torch.Scale = 6;
    window._game = game;
    game.Bounds();
    game.Clear("black");
    game.player = new Player(game);
    game.player.DrawIndex(9);
    game.origTest = new Torch.Sprite(game, game.canvasNode.width - 50, 0);
    game.origTest.Bind.WebGLTexture("enemy");
    game.origTest.DrawIndex(10);
    return game.Add(new Torch.AmbientLight(0xffffff));
  };

  Draw = function(game) {};

  Update = function(game) {};

  Game.Start(Load, Update, Draw, Init);

}).call(this);
