// Generated by CoffeeScript 1.10.0
(function() {
  var Audio, AudioPlayer;

  Audio = (function() {
    Audio.prototype.audioContext = null;

    Audio.prototype.MasterVolume = 1;

    function Audio(game) {
      this.game = game;
      this.GetAudioContext();
    }

    Audio.prototype.GetAudioContext = function() {
      var e, error;
      try {
        window.AudioContext = window.AudioContext || window.webkitAudioContext;
        return this.audioContext = new AudioContext();
      } catch (error) {
        e = error;
        return console.warn("Unable to initialize audio...");
      }
    };

    Audio.prototype.DecodeAudioData = function(data, callback) {
      return this.audioContext.decodeAudioData(data, function(buffer) {
        return callback(buffer);
      });
    };

    Audio.prototype.CreateAudioPlayer = function() {
      return new AudioPlayer(this);
    };

    return Audio;

  })();

  AudioPlayer = (function() {
    function AudioPlayer(aud) {
      this.audioContext = aud.audioContext;
      this.game = aud.game;
    }

    AudioPlayer.prototype.CreateGain = function(gain) {
      var gainNode;
      if (gain == null) {
        gain = 1;
      }
      gainNode = this.audioContext.createGain();
      gainNode.gain.value = gain;
      return gainNode;
    };

    AudioPlayer.prototype.PlaySound = function(id, time, filters) {
      var filter, i, index, lastFilter, len, source;
      if (time == null) {
        time = 0;
      }
      if (filters == null) {
        filters = null;
      }
      source = this.audioContext.createBufferSource();
      source.buffer = this.game.Assets.Audio[id].audioData;
      if (this.game.Audio.MasterVolume !== 1) {
        if (filters === null) {
          filters = [this.CreateGain(this.game.Audio.MasterVolume)];
        } else {
          filters.push(this.CreateGain(this.game.Audio.MasterVolume));
        }
      }
      if (filters !== null) {
        lastFilter = null;
        for (index = i = 0, len = filters.length; i < len; index = ++i) {
          filter = filters[index];
          if (lastFilter === null) {
            source.connect(filter);
          } else {
            lastFilter.connect(filter);
          }
          lastFilter = filter;
          if (index === filters.length - 1) {
            filter.connect(this.audioContext.destination);
            source.start(time);
            return;
          }
        }
      }
      source.connect(this.audioContext.destination);
      return source.start(time);
    };

    return AudioPlayer;

  })();

  Torch.Audio = Audio;

}).call(this);
