// Generated by CoffeeScript 1.10.0
(function() {
  var Camera;

  Camera = (function() {
    Camera.prototype.position = null;

    function Camera(game) {
      this.game = game;
      this.position = new Torch.Point(0, 0);
    }

    Camera.prototype.Update = function() {};

    return Camera;

  })();

  Torch.Camera = Camera;

}).call(this);
