// Generated by CoffeeScript 1.11.1
(function() {
  var Debug;

  Debug = (function() {
    function Debug(game) {
      this.game = game;
    }

    return Debug;

  })();

  Torch.Debug = Debug;

}).call(this);
