// Generated by CoffeeScript 1.10.0
(function() {
  var HookManager;

  HookManager = (function() {
    HookManager.prototype.positionTransform = null;

    function HookManager(game) {
      this.game = game;
      this.positionTransform = new Torch.Point(0, 0);
    }

    return HookManager;

  })();

  Torch.HookManager = HookManager;

}).call(this);
