// Generated by CoffeeScript 1.11.1
(function() {
  var Key, Keys, exports;

  exports = this;

  Key = (function() {
    Key.MixIn(Torch.EventDispatcher);

    Key.prototype.down = false;

    function Key(keyCode) {
      this.keyCode = keyCode;
      this.InitEventDispatch();
    }

    return Key;

  })();

  Keys = (function() {
    Keys.MixIn(Torch.EventDispatcher);

    function Keys() {
      this.InitKeys();
    }

    Keys.prototype.InitKeys = function() {
      var _char, _keys, i;
      _keys = this;
      i = 0;
      while (i < 230) {
        _char = String.fromCharCode(i).toUpperCase();
        _keys[_char] = new Key(i);
        i++;
      }
      _keys["Space"] = new Key(32);
      _keys["LeftArrow"] = new Key(37);
      _keys["RightArrow"] = new Key(39);
      _keys["UpArrow"] = new Key(38);
      return _keys["DownArrow"] = new Key(40);
    };

    return Keys;

  })();

  Torch.Keys = Keys;

}).call(this);
