// Generated by CoffeeScript 1.10.0
(function() {
  var Keys, exports;

  exports = this;

  Keys = (function() {
    function Keys() {
      this.InitKeys();
    }

    Keys.prototype.InitKeys = function() {};

    return Keys;

  })();

}).call(this);
