// Generated by CoffeeScript 1.10.0
(function() {
  var Mouse;

  Mouse = (function() {
    function Mouse(game) {
      this.game = game;
      this.x = 0;
      this.y = 0;
      this.down = false;
    }

    Mouse.prototype.SetMousePos = function(c, evt) {
      var rect;
      rect = c.getBoundingClientRect();
      this.x = evt.clientX - rect.left;
      return this.y = evt.clientY - rect.top;
    };

    Mouse.prototype.GetRectangle = function() {
      return new Torch.Rectangle(this.x, this.y, 5, 5);
    };

    return Mouse;

  })();

  Torch.Mouse = Mouse;

}).call(this);
