// Generated by CoffeeScript 1.10.0
(function() {
  var Mouse;

  Mouse = (function() {
    function Mouse(game) {
      this.game = game;
      this.x = 0;
      this.y = 0;
      this.down = false;
    }

    Mouse.prototype.SetMousePos = function(c, evt) {
      var rect;
      rect = c.getBoundingClientRect();
      this.x = evt.pageX;
      this.y = evt.pageY;
      if (this.game.gl_camera) {
        return this.SetThreePosition(evt);
      }
    };

    Mouse.prototype.SetThreePosition = function(evt) {
      var camera, dir, distance, pos, vector;
      vector = new THREE.Vector3();
      camera = this.game.gl_camera;
      vector.set((evt.clientX / window.innerWidth) * 2 - 1, -(evt.clientY / window.innerHeight) * 2 + 1, 0.5);
      vector.unproject(camera);
      dir = vector.sub(camera.position).normalize();
      distance = -camera.position.z / dir.z;
      pos = camera.position.clone().add(dir.multiplyScalar(distance));
      this.x = pos.x + window.innerWidth / 1.45;
      return this.y = -pos.y + window.innerHeight / 1.45;
    };

    Mouse.prototype.GetRectangle = function() {
      return new Torch.Rectangle(this.x - this.game.Viewport.x, this.y - this.game.Viewport.y, 5, 5);
    };

    return Mouse;

  })();

  Torch.Mouse = Mouse;

}).call(this);
