// Generated by CoffeeScript 1.10.0
(function() {
  var slice = [].slice;

  window.onerror = function() {
    var args, errorObj;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    if (!window.Torch.STRICT_ERRORS) {
      return;
    }
    document.body.style.backgroundColor = "black";
    errorObj = args[4];
    if (errorObj !== void 0) {
      return Torch.FatalError(errorObj);
    } else {
      return Torch.FatalError("An error has occured");
    }
  };

}).call(this);
