// Generated by CoffeeScript 1.10.0
(function() {
  var slice = [].slice;

  Function.prototype.MixIn = Function.prototype.is = function(otherFunction) {
    var items, key, proto, value;
    proto = this.prototype;
    items = Object.create(otherFunction.prototype);
    for (key in items) {
      value = items[key];
      proto[key] = value;
    }
    return this;
  };

  String.prototype.format = function() {
    var args, replacer;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    replacer = function(match, number) {
      if (typeof args[number] !== void 0) {
        return args[number];
      }
      if (typeof args[number] === void 0) {
        return match;
      }
    };
    return this.replace(/{(\d+)}/g, replacer);
  };

  String.prototype.capitalize = function() {
    return this.charAt(0).toUpperCase() + this.slice(1);
  };

  String.prototype.unCapitalize = function() {
    return this.charAt(0).toLowerCase() + this.slice(1);
  };

}).call(this);
