// Generated by CoffeeScript 1.10.0
(function() {
  var Trashable;

  Trashable = (function() {
    function Trashable() {}

    Trashable.prototype.trash = false;

    Trashable.prototype.Trash = function() {
      this.trash = true;
      return this;
    };

    return Trashable;

  })();

}).call(this);
