// Generated by CoffeeScript 1.10.0
(function() {
  var Animation;

  Animation = (function() {
    function Animation(game) {
      this.game = game;
    }

    Animation.prototype.Run = function() {
      if (this.animating) {
        that.Update();
      }
      if (this.Kill && this.hasRun) {
        return this.Stop();
      }
    };

    Animation.prototype.Start = function() {
      return this.animating = true;
    };

    return Animation;

  })();

}).call(this);
