// Generated by CoffeeScript 1.10.0
(function() {
  var Electron;

  Electron = (function() {
    function Electron() {}

    Electron.prototype.Import = function() {
      return Torch.fs = require("fs");
    };

    return Electron;

  })();

  Torch.Electron = new Electron();

}).call(this);
