// Generated by CoffeeScript 1.10.0
(function() {
  var Electron;

  Electron = (function() {
    function Electron() {}

    Electron.Import = function() {
      Torch.ELECTRON = true;
      return Torch.fs = require("fs");
    };

    return Electron;

  })();

}).call(this);
