// Generated by CoffeeScript 1.10.0
(function() {
  var Keys;

  Keys = (function() {
    function Keys() {
      this.InitKeys();
    }

    Keys.prototype.InitKeys = function() {
      var _char, _keys, i, results;
      _keys = this;
      i = 0;
      results = [];
      while (i < 230) {
        _char = String.fromCharCode(i).toUpperCase();
        switch (i) {
          case 37:
            _keys["LeftArrow"] = {
              down: false
            };
            break;
          case 38:
            _keys["UpArrow"] = {
              down: false
            };
            break;
          case 39:
            _keys["RightArrow"] = {
              down: false
            };
            break;
          case 40:
            _keys["DownArrow"] = {
              down: false
            };
            break;
          default:
            _keys[_char] = {
              down: false
            };
        }
        results.push(_keys["Space"] = {
          down: false
        });
      }
      return results;
    };

    return Keys;

  })();

}).call(this);
