// Generated by CoffeeScript 1.11.1
(function() {
  var ParticleEmitter,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ParticleEmitter = (function(superClass) {
    extend(ParticleEmitter, superClass);

    function ParticleEmitter(x, y, particleDecayTime, step, once) {
      if (once == null) {
        once = false;
      }
      this.InitSprite(x, y);
      this.PARTICLE_DECAY_TIME = particleDecayTime;
      this.STEP = step;
      this.elapsedTime = 0;
      this.OnEmit = null;
      this.once = once;
    }

    ParticleEmitter.prototype.Update = function() {
      ParticleEmitter.__super__.Update.call(this);
      this.elapsedTime += this.game.deltaTime;
      if (this.elapsedTime >= this.STEP) {
        this.Emit();
        return that.elapsedTime = 0;
      }
    };

    return ParticleEmitter;

  })(Torch.GhostSprite);

}).call(this);
