// Generated by CoffeeScript 1.10.0
(function() {
  var ParticleEmitter,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ParticleEmitter = (function(superClass) {
    extend(ParticleEmitter, superClass);

    function ParticleEmitter(x, y, particleDecayTime, step, once) {}

    return ParticleEmitter;

  })(Torch.GhostSprite);

}).call(this);
