// Generated by CoffeeScript 1.10.0
(function() {
  var PlayList, exports;

  exports = Torch.Sound;

  PlayList = (function() {
    function PlayList(game, songList) {
      this.game = game;
      this.songList = songList;
      this.currentSong = playList[0];
      this.index = 0;
    }

    return PlayList;

  })();

}).call(this);
