// Generated by CoffeeScript 1.10.0
(function() {
  Torch.Style = function() {
    var body, canvas, canvasContainer;
    canvasContainer = document.getElementById("canvas-container");
    canvasContainer.style.width = "100%";
    canvasContainer.style.textAlign = "center";
    body = document.body;
    body.style.backgroundColor = "black";
    body.style.overflow = "hidden";
    canvas = document.getElementsByTagName("CANVAS");
    return canvas.style.cursor = "pointer";
  };

}).call(this);
