// Generated by CoffeeScript 1.11.1
(function() {
  var TweenTask;

  TweenTask = (function() {
    function TweenTask() {}

    TweenTask.prototype.trash = false;

    constructor(TweenTask.game, TweenTask.object, TweenTask.time, TweenTask.props, TweenTask.type, TweenTask.finish)(function() {
      this.t = 0;
      this.steps = GetSteps();
      this.onStep = null;
      return this.onFinish = null;
    });

    TweenTask.prototype.Update = function() {
      this.t += this.game.deltaTime;
      this.Step();
      if (this.t >= time) {
        return this.trash = true;
      }
    };

    TweenTask.prototype.Step = function() {
      var prop;
      for (prop in props) {
        this.object[prop] += this.steps[prop];
      }
      if (this.onStep !== null) {
        return this.onStep();
      }
    };

    return TweenTask;

  })();

}).call(this);
