// Generated by CoffeeScript 1.10.0
(function() {
  var WebGLRenderer, exports;

  exports = this;

  WebGLRenderer = (function() {
    function WebGLRenderer(sprite) {
      this.sprite = sprite;
    }

    WebGLRenderer.prototype.Draw = function() {};

    return WebGLRenderer;

  })();

}).call(this);
