// Generated by CoffeeScript 1.10.0
(function() {
  var WebGLRenderer, exports;

  exports = this;

  WebGLRenderer = (function() {
    function WebGLRenderer() {}

    WebGLRenderer.prototype.Draw = function() {};

    return WebGLRenderer;

  })();

}).call(this);
