// Generated by CoffeeScript 1.10.0
(function() {
  var Shape;

  Shape = (function() {
    function Shape() {}

    Shape.prototype.Render = function() {
      var canvas;
      return canvas = document.create;
    };

    return Shape;

  })();

}).call(this);
