// Generated by CoffeeScript 1.10.0
(function() {
  var SpriteGrid;

  SpriteGrid = (function() {
    function SpriteGrid(game, gridXml) {
      this.game = game;
      this.gridXml = gridXml;
      this.ParseXml();
    }

    SpriteGrid.prototype.ParseXml = function() {
      var parser, root, sprites, xmlDoc;
      parser = new DOMParser();
      xmlDoc = parser.parseFromString(this.gridXml, "text/xml");
      root = xmlDoc.getElementsByTagName("SpriteGrid")[0];
      if (root === null) {
        this.game.FatalError("Unable to parse SpriteGrid XML, no SpriteGrid tag");
      }
      return sprites = root.getElementsByTagName("Sprite");
    };

    return SpriteGrid;

  })();

}).call(this);
