// Generated by CoffeeScript 1.10.0
(function() {
  var SpriteGrid;

  SpriteGrid = (function() {
    function SpriteGrid(game, gridXml) {
      this.game = game;
      this.gridXml = gridXml;
      this.ParseXml();
    }

    SpriteGrid.prototype.ParseXml = function() {
      var i, len, parser, results, root, sprite, sprites, xmlDoc;
      parser = new DOMParser();
      xmlDoc = parser.parseFromString(this.gridXml, "text/xml");
      root = xmlDoc.getElementsByTagName("SpriteGrid")[0];
      if (root === null) {
        this.game.FatalError("Unable to parse SpriteGrid XML, no SpriteGrid tag");
      }
      sprites = root.getElementsByTagName("Sprite");
      window.nnodes = sprites;
      results = [];
      for (i = 0, len = sprites.length; i < len; i++) {
        sprite = sprites[i];
        results.push(console.log(sprite.parentNode));
      }
      return results;
    };

    return SpriteGrid;

  })();

  Torch.SpriteGrid = SpriteGrid;

}).call(this);
