// Generated by CoffeeScript 1.10.0
(function() {
  var Text, _measureCanvas,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  _measureCanvas = document.createElement("CANVAS");

  _measureCanvas.width = 500;

  _measureCanvas.height = 500;

  Text = (function(superClass) {
    extend(Text, superClass);

    Text.prototype.TEXT = true;

    Text.measureCanvas = _measureCanvas.getContext("2d");

    function Text(game, x, y, data) {
      this.InitText(game, x, y, data);
    }

    Text.prototype.InitText = function(game, x, y, data) {
      this.InitSprite(game, x, y);
      this.data = data;
      this.font = "Arial";
      this.fontSize = 16;
      this.fontWeight = "";
      this.color = "#2b4531";
      this.text = "";
      this.lastText = "";
      this.width = 100;
      this.height = 100;
      this.Size.scale = {
        width: 1,
        height: 1
      };
      return this.Init();
    };

    Text.prototype.Init = function() {
      if (this.data.font) {
        this.font = this.data.font;
      }
      if (this.data.fontSize) {
        this.fontSize = this.data.fontSize;
      }
      if (this.data.fontWeight) {
        this.fontWeight = this.data.fontWeight;
      }
      if (this.data.color) {
        this.color = this.data.color;
      }
      if (this.data.text) {
        this.text = this.data.text;
      }
      if (this.data.rectangle) {
        this.rectangle = this.data.rectangle;
      }
      if (this.data.buffHeight) {
        this.buffHeight = this.data.buffHeight;
      }
      return this.Render();
    };

    Text.prototype.Render = function() {
      var canvas, cnv, image;
      cnv = document.createElement("CANVAS");
      Text.measureCanvas.font = this.fontSize + "px " + this.font;
      cnv.width = Text.measureCanvas.measureText(this.text).width;
      cnv.height = this.fontSize;
      if (this.buffHeight) {
        cnv.height += this.buffHeight;
      }
      canvas = cnv.getContext("2d");
      canvas.fillStyle = this.color;
      canvas.font = this.fontWeight + " " + this.fontSize + "px " + this.font;
      canvas.fillText(this.text, 0, cnv.height);
      image = new Image();
      image.src = cnv.toDataURL();
      image.onload = (function(_this) {
        return function() {
          if (_this.GL) {
            if (_this.Three()) {
              _this.Three().Remove();
            }
            return _this.Bind.WebGLTexture({
              gl_2d_canvas_generated_image: true,
              width: image.width,
              height: image.height,
              texture: new THREE.TextureLoader().load(image.src)
            });
          } else {
            return _this.Bind.Texture(image);
          }
        };
      })(this);
      this.rectangle.width = cnv.width;
      return this.rectangle.height = this.fontSize;
    };

    Text.prototype.Update = function() {
      Text.__super__.Update.call(this);
      return this.UpdateText();
    };

    Text.prototype.UpdateText = function() {
      if (this.text !== this.lastText) {
        this.Render();
        return this.lastText = this.text;
      }
    };

    return Text;

  })(Sprite);

}).call(this);
