// Generated by CoffeeScript 1.10.0
(function() {
  var ThreeSprite,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ThreeSprite = (function(superClass) {
    extend(ThreeSprite, superClass);

    function ThreeSprite(sprite, material, shape) {
      var object;
      object = new THREE.Mesh(shape, material);
      object.position.z = this.sprite.Rectangle.z;
      object.position.x = this.sprite.Rectangle.x;
      object.position.y = this.sprite.Rectangle.y;
      object.name = sprite._torch_uid;
      sprite.game.gl_scene.add(object);
      this.Entity(object);
    }

    ThreeSprite.prototype.Rotation = function(arg) {
      return this.entity.rotation.z = arg;
    };

    ThreeSprite.prototype.Opacity = function(arg) {
      return this.entity.materials[0].opacity = arg;
    };

    ThreeSprite.prototype.DrawIndex = function(arg) {
      return this.entity.renderOrder = arg;
    };

    return ThreeSprite;

  })(ThreeEntity);

}).call(this);
