// Generated by CoffeeScript 1.10.0
(function() {
  var ThreeEntity, exports;

  exports = this;

  ThreeEntity = (function() {
    function ThreeEntity() {}

    ThreeEntity.prototype.game = null;

    ThreeEntity.prototype.entity = null;

    ThreeEntity.prototype._torch_add = "Three";

    ThreeEntity.prototype.Entity = function(entity) {
      return this.entity = entity;
    };

    ThreeEntity.prototype.Remove = function() {
      if (this.game !== null) {
        return this.game.gl_scene.remove(this.entity);
      }
    };

    ThreeEntity.prototype.Position = function(plane, value) {
      if (value === void 0) {
        return this.entity.position[plane];
      }
      this.entity.position[plane] = value;
      return this;
    };

    ThreeEntity.prototype.Update = function() {};

    return ThreeEntity;

  })();

  exports.ThreeEntity = ThreeEntity;

}).call(this);
