// Generated by CoffeeScript 1.10.0
(function() {
  var Bush, MapPiece, exports,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  exports = this;

  MapPiece = (function(superClass) {
    extend(MapPiece, superClass);

    MapPiece.prototype.MAPPIECE = true;

    MapPiece.prototype.identifier = 0;

    MapPiece.prototype.textureId = "";

    MapPiece.prototype.data = null;

    function MapPiece(game, rawData) {
      this.data = this.GetData(rawData);
      this.InitSprite(game, this.data.position.x, this.data.position.y);
      this.Bind.Texture(this.textureId);
    }

    MapPiece.prototype.GetData = function(rawData) {
      var data;
      data = {};
      data.position = {
        x: parseInt(rawData[0], 16),
        y: parseInt(rawData[1], 16)
      };
      return data;
    };

    return MapPiece;

  })(Torch.Sprite);

  Bush = (function(superClass) {
    extend(Bush, superClass);

    function Bush() {
      return Bush.__super__.constructor.apply(this, arguments);
    }

    Bush.prototype.textureId = "bush";

    return Bush;

  })(MapPiece);

  exports.MapPieces = {
    Bush: Bush
  };

}).call(this);
