// Generated by CoffeeScript 1.10.0
(function() {
  var MapPiece, exports,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  exports = this;

  MapPiece = (function(superClass) {
    extend(MapPiece, superClass);

    MapPiece.prototype.identifier = 0;

    function MapPiece(game, data) {
      this.InitSprite(game, 50, 50);
      this.Bind.Texture("bush");
    }

    return MapPiece;

  })(Torch.Sprite);

  exports.MapPiece = MapPiece;

}).call(this);
