// Generated by CoffeeScript 1.10.0
(function() {
  var Game;

  Game = (function() {
    function Game(canvasId, width, height, name, graphicsType) {
      if (graphicsType == null) {
        graphicsType = Torch.CANVAS;
      }
      if (graphicsType === Torch.CANVAS) {
        return new Torch.CanvasGame(canvasId, width, height, name, graphicsType);
      }
      if (graphicsType === Torch.WEBGL) {
        return new Torch.WebGLGame(canvasId, width, height, name, graphicsType);
      }
    }

    return Game;

  })();

  Torch.Game = Game;

}).call(this);
