// Generated by CoffeeScript 1.12.1
(function() {
  module.exports = {
    RunTests: function(tests, fileName) {
      var e, i, len, results, t;
      try {
        results = [];
        for (i = 0, len = tests.length; i < len; i++) {
          t = tests[i];
          results.push(t());
        }
        return results;
      } catch (error) {
        e = error;
        console.log("===TESTS FAILED===\n===" + fileName + "===\n");
        throw e;
      } finally {
        console.log("===TESTS PASSED===\n" + fileName + "\n" + tests.length + " passed");
      }
    }
  };

}).call(this);
