// Generated by CoffeeScript 1.12.1
(function() {
  var T, Torch, test, tests, torchTest;

  test = require("unit.js");

  torchTest = require("./torch-test.js");

  Torch = require("../../../Builds/torch-latest.js").Torch;

  T = Torch.Util;

  tests = [];

  tests.push(function() {
    var arrayBefore, total;
    arrayBefore = [1, 1, 1];
    total = 0;
    T.Array(arrayBefore).All(function(item) {
      return total += item;
    });
    return test.assert(total === 3);
  });

  tests.push(function() {
    var foundItem;
    foundItem = T.Array([1, 2, null, 'l', false, "50", "f"]).Find(function(item) {
      return item === "50";
    });
    return test.assert(foundItem === "50");
  });

  tests.push(function() {
    var arrayHasEvens, arrayHasObjectsWithProp;
    arrayHasEvens = T.Array([1, 2, 3]).Filter(function(item) {
      return item % 2 === 0;
    });
    arrayHasObjectsWithProp = T.Array([
      {
        x: 0,
        y: 0
      }, {
        x: 1,
        y: 1
      }
    ]).Filter(function(item) {
      return item.x === 1;
    });
    test.assert(arrayHasEvens.length === 1);
    test.assert(arrayHasEvens[0] === 2);
    return test.assert(arrayHasObjectsWithProp.length === 1);
  });

  module.exports = function() {
    return torchTest.RunTests(tests, __filename);
  };

}).call(this);
